[versions]
flyway = "11.5.0"
tbdLibs = "2026.01.22-09.16-1d3f6039"
sykepengerGradlePlugins = "20261001.1830"

[libraries]
flyway-database-postgresql = { module = "org.flywaydb:flyway-database-postgresql", version.ref = "flyway" }
hikariCP = "com.zaxxer:HikariCP:6.3.0"
kotliquery = "com.github.seratch:kotliquery:1.9.1"
mockk = "io.mockk:mockk:1.14.11"
postgresql = "org.postgresql:postgresql:42.7.13"

rapidsAndRivers = "com.github.navikt:rapids-and-rivers:2026091610031789545782"

tbdLibs-postgresTestdatabaser = { module = "com.github.navikt.tbd-libs:postgres-testdatabaser", version.ref = "tbdLibs" }
tbdLibs-rapidsAndRiversTest = { module = "com.github.navikt.tbd-libs:rapids-and-rivers-test", version.ref = "tbdLibs" }

[plugins]
sykepenger-deployable = { id = "no.nav.sykepenger.deployable", version.ref = "sykepengerGradlePlugins" }
