apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: spregulering
  namespace: tbd
  labels:
    team: tbd
spec:
  image: {{image}}
  port: 8080
  strategy:
    type: Recreate
  liveness:
    path: isalive
    initialDelay: 5
  readiness:
    path: isready
    initialDelay: 5
  preStopHook:
    http:
      path: /stop
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas:
    min: 2
    max: 6
  kafka:
    pool: nav-prod
  prometheus:
    enabled: true
    path: /metrics
  accessPolicy:
    outbound:
      rules:
        - application: logging
          namespace: nais-system
  gcp:
    sqlInstances:
      - type: POSTGRES_17
        diskAutoresize: true
        tier: db-custom-1-3840
        name: spregulering
        databases:
          - name: spregulering
            envVarPrefix: DATABASE
  secureLogs:
    enabled: true
  env:
    - name: KAFKA_CONSUMER_GROUP_ID
      value: spregulering-v2
    - name: KAFKA_RAPID_TOPIC
      value: tbd.rapid.v1
    - name: KAFKA_RESET_POLICY
      value: earliest
    - name: KAFKA_EXTRA_TOPIC
      value: tbd.teknisk.v1
  observability:
    logging:
      destinations:
        - id: elastic
        - id: loki
